### ISSUE TITLE
Implement proper image (re)sizing

### ISSUE THREAD

**Issue by craigrosie** [craigrosie/craigrosie.github.io#9]
```css
img {
  max-width: 100%;
  height: auto;
}
```
with `width` & `heigh` attributes in `img` element (or CSS).
